### ISSUE TITLE
Error: Failed to load library "SDL2" from ""

### ISSUE THREAD

**Issue by ajbdev** [smack0007/deno-sdl2-ffi#1]
When I clone the repo and attempt to run any of the demos from a windows powershell, I see the following:
```
PS C:\Users\andyb\src\SDL_ts> deno task run:doom-fire
Task run:doom-fire export SDL_TS_ENV_DIR=$INIT_CWD && cd ./examples/doom-fire && deno run --unstable --allow-env --allow-ffi --allow-read=../.. $DENO_FLAGS ./main.ts
Error: Failed to load library "SDL2" from ""
    at Function.denoLoadLibrary [as loadLibrary] (file:///C:/Users/andyb/src/SDL_ts/src/deno/_library.ts:123:9)
    at Module.Init (file:///C:/Users/andyb/src/SDL_ts/src/SDL/functions.ts:353:23)
    at main (file:///C:/Users/andyb/src/SDL_ts/examples/doom-fire/main.ts:53:7)
    at file:///C:/Users/andyb/src/SDL_ts/examples/doom-fire/main.ts:191:13
Caused by AggregateError
    at Function.denoLoadLibrary [as loadLibrary] (file:///C:/Users/andyb/src/SDL_ts/src/deno/_library.ts:125:5)
    at Module.Init (file:///C:/Users/andyb/src/SDL_ts/src/SDL/functions.ts:353:23)
    at main (file:///C:/Users/andyb/src/SDL_ts/examples/doom-fire/main.ts:53:7)
    at file:///C:/Users/andyb/src/SDL_ts/examples/doom-fire/main.ts:191:13
PS C:\Users\andyb\src\SDL_ts> ls
```

It seems the .env.windows file is not loading correctly. Any ideas? Let me know if you need more info.

**Comment by smack0007** [comment]
I always run things git-bash so it would be interesting to know if that works for you. Other than that I'll have to take a look at when I get time.

Just taking a stab at it without actually debugging it though: "export SDL_TS_ENV_DIR=$INIT_CWD" will more than likely not work in PowerShell and that environment variable is how the library knows where to look for the DLL.

Update:
It looks like I'm not using the environment variables feature from deno tasks correctly:
https://deno.land/manual@v1.32.3/tools/task_runner#setting-environment-variables-for-a-command

Maybe just removing the "export" will help? As I said I will try and test this myself when I can.

**Comment by smack0007** [comment]
Ok I sat down and tested it and it should work now. Had to change when the environment variables were being set.

https://github.com/smack0007/SDL_ts/commit/212b5dac7cbe413251d969b9ace3d48f9fd87c6e

Please try it again with the latest changes in main.

**Comment by ajbdev** [comment]
Still see the same problem on the most recent main commit:

```
PS C:\Users\andyb\src\SDL_ts> git rev-parse HEAD
212b5dac7cbe413251d969b9ace3d48f9fd87c6e
PS C:\Users\andyb\src\SDL_ts> deno task run:doom-fire
Warning deno task is unstable and may drastically change in the future
Task run:doom-fire cd ./examples/doom-fire && SDL_TS_ENV_DIR=$INIT_CWD deno run --unstable --allow-env --allow-ffi --allow-read=../.. $DENO_FLAGS ./main.ts
Error: Failed to load library "SDL2" from ""
    at Function.denoLoadLibrary [as loadLibrary] (file:///C:/Users/andyb/src/SDL_ts/src/deno/_library.ts:118:9)
    at Module.Init (file:///C:/Users/andyb/src/SDL_ts/src/SDL/functions.ts:353:23)
    at main (file:///C:/Users/andyb/src/SDL_ts/examples/doom-fire/main.ts:53:7)
    at file:///C:/Users/andyb/src/SDL_ts/examples/doom-fire/main.ts:191:13
Caused by AggregateError
    at Function.denoLoadLibrary [as loadLibrary] (file:///C:/Users/andyb/src/SDL_ts/src/deno/_library.ts:120:5)
    at Module.Init (file:///C:/Users/andyb/src/SDL_ts/src/SDL/functions.ts:353:23)
    at main (file:///C:/Users/andyb/src/SDL_ts/examples/doom-fire/main.ts:53:7)
    at file:///C:/Users/andyb/src/SDL_ts/examples/doom-fire/main.ts:191:13
```

FYI, this happens on both PS and git bash. I'll do some more digging on this when I have some time later this evening.

**Comment by ajbdev** [comment]
I dug into this a bit more tonight, but I'm afraid I don't have any kind of solution -- it appears that $INIT_CWD doesn't get populated from deno - if I put a different value into SDL_TS_ENV_DIR I'm able to read it out in deno just fine. E.g.,: in deno.json:

```"
run:doom-fire": "cd ./examples/doom-fire && SDL_TS_ENV_DIR=TESTING deno run --unstable --allow-env --allow-ffi --allow-read=../.. $DENO_FLAGS ./main.ts",
```

In src\deno\_library.ts

```
    console.log(Deno.env.get(ENV_ENV_DIR));
```

Produces:

```
Task run:doom-fire cd ./examples/doom-fire && SDL_TS_ENV_DIR=TESTING deno run --unstable --allow-env --allow-ffi --allow-read=../.. $DENO_FLAGS ./main.ts
TESTING
Error: Failed to load library "SDL2" from ""
    at Function.denoLoadLibrary [as loadLibrary] (file:///C:/Users/andyb/src/SDL_ts/src/deno/_library.ts:124:9)
    at Module.Init (file:///C:/Users/andyb/src/SDL_ts/src/SDL/functions.ts:353:23)
    at main (file:///C:/Users/andyb/src/SDL_ts/examples/doom-fire/main.ts:53:7)
    at file:///C:/Users/andyb/src/SDL_ts/examples/doom-fire/main.ts:191:13
Caused by AggregateError
    at Function.denoLoadLibrary [as loadLibrary] (file:///C:/Users/andyb/src/SDL_ts/src/deno/_library.ts:126:5)
    at Module.Init (file:///C:/Users/andyb/src/SDL_ts/src/SDL/functions.ts:353:23)
    at main (file:///C:/Users/andyb/src/SDL_ts/examples/doom-fire/main.ts:53:7)
    at file:///C:/Users/andyb/src/SDL_ts/examples/doom-fire/main.ts:191:13
```


Versions btw:
```
PS C:\Users\andyb\src\SDL_ts> deno --version
deno 1.25.4 (release, x86_64-pc-windows-msvc)
v8 10.7.193.3
typescript 4.7.4
```

**Comment by smack0007** [comment]
Your version of deno is too old. The $INIT_CWD is relatively new (introduced in 1.27). Also with that version of deno your next problem will be with the FFI as that interface has changed in the last few versions. You should upgrade to the newest version.

**Comment by ajbdev** [comment]
That's right, an upgrade fixed it -- thank you!
